<script>
	function fibonacci(limit) {
		let fibonacci = [];
		let n2 = 0;
		let n1 = 1;
		let current = 0;
		let oldCurrent;
		let oldN1;
		while (current < limit) {
			current = n2 + n1;
			oldN1 = n1;
			n2 = oldN1;
			oldCurrent = current;
			n1 = oldCurrent;

			fibonacci.push(current);
		}
		return fibonacci.slice(0, fibonacci.length - 1);
	}

	function evenFibonacciArray(array) {
		return array.filter((n) => n % 2 === 0);
	}

	function sum(evenNumbers) {
		return evenNumbers.reduce((a, b) => a + b, 0);
	}

	let fibonacciArray = fibonacci(4000000);

	let evenNumbers = evenFibonacciArray(fibonacciArray);

	let answer = sum(evenNumbers);

	console.log(answer);
</script>

<h1>Problem 2</h1>
<p>
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting
	with 1 and 2, the first 10 terms will be:
</p>
<p class="center">1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>
<p>
	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find
	the sum of the even-valued terms.
</p>
<p class="answer">{answer}</p>

<style>
	h1 {
		text-align: center;
		margin: 1.5em;
	}
	p {
		text-align: center;
	}
	.answer {
		text-align: center;
		font-size: xxx-large;
		align-items: center;
	}
</style>
