<script>
	let answer = 0;
</script>

<h1>Problem 2</h1>
<p>
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting
	with 1 and 2, the first 10 terms will be:
</p>
<p class="center">1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>
<p>
	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find
	the sum of the even-valued terms.
</p>
<p class="answer">{answer}</p>

<style>
	h1 {
		text-align: center;
		margin: 1.5em;
	}
	p {
		text-align: center;
	}
	.answer {
		text-align: center;
		font-size: xxx-large;
		align-items: center;
	}
</style>
